In [1]:
import tensorflow as tf
import numpy as np
        
def get_value(node):
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())
        node_val = sess.run(node)
    return node_val
        
def get_values(node):
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())
        nodes_val = sess.run(nodes)
    return nodes_val
        
def get_shape(node):
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())
        nodes_val = sess.run(nodes)
    return nodes_val

In [2]:
answer_step_indices = tf.constant(np.asarray([0, 2, 3, 4, 0]))
get_value(answer_step_indices)

array([0, 2, 3, 4, 0])

In [3]:
targets = tf.constant([0, 1, 0, 0, 0])
answer_predictions = tf.constant([0, 1, 1, 0, 1])
answer_correctness = tf.equal(targets, answer_predictions)
get_value(answer_correctness)

array([ True,  True, False,  True, False])

In [6]:
bool_product = tf.reduce_prod(tf.cast(answer_correctness)
get_value(bool_product)

TypeError: Value passed to parameter 'input' has DataType bool not in list of allowed values: float32, float64, int32, uint8, int16, int8, complex64, int64, qint8, quint8, qint32, bfloat16, uint16, complex128, float16, uint32, uint64

In [4]:
correct_answer_step_indices = tf.boolean_mask(answer_step_indices, answer_correctness)
get_value(correct_answer_step_indices)

array([0, 2, 4])